apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs-apm-2
    tags.datadoghq.com/env: "devlab"
    tags.datadoghq.com/version: "1"
    tags.datadoghq.com/service: "nodejs-apm-2"
  name: nodejs-apm-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-apm-2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-apm-2
        version: "1"
        tags.datadoghq.com/env: "devlab"
        tags.datadoghq.com/version: "1"
    spec:
      containers:
      - image: absalon1000rr/nodejs-apm-2
        name: nodejs-apm-2
        env:
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_ENV
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/env']
          - name: DD_VERSION
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/version']
          - name: DD_SERVICE
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/service']
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_APM_NON_LOCAL_TRAFFIC
            value: "true"
        #imagePullPolicy: Never
        resources: {}
        ports:
          - containerPort: 8082